SELECT
    PREFECTURE.PF_CODE AS `都道府県コード`,
    PREFECTURE.PF_NAME AS `都道府県名`,
    ROUND(100.0 * CAST(HOSPITALIZATION.INP_YES AS FLOAT) / CAST((HOSPITALIZATION.INP_YES + HOSPITALIZATION.INP_NO + HOSPITALIZATION.UNIDENTIFIED) AS FLOAT), 1) AS `入院率`
FROM HOSPITALIZATION
INNER JOIN PREFECTURE ON PREFECTURE.PF_CODE = HOSPITALIZATION.PF_CODE
ORDER BY
    `入院率` DESC,
    `都道府県コード` ASC;
